import { Pokemon, Move } from './types';

export const MOVES_DATABASE: Record<string, Move> = {
  Thunderbolt: {
    name: 'Thunderbolt',
    type: 'Electric',
    power: 90,
    accuracy: 100,
    category: 'Special',
    effect: 'paralyze',
    description: 'A strong electrical attack. May paralyze the foe.'
  },
  IronTail: {
    name: 'Iron Tail',
    type: 'Steel',
    power: 100,
    accuracy: 75,
    category: 'Physical',
    description: 'A hard steel-tail smash. High damage, lower accuracy.'
  },
  QuickAttack: {
    name: 'Quick Attack',
    type: 'Flying',
    power: 40,
    accuracy: 100,
    category: 'Physical',
    description: 'An extremely fast dash attack. Hits reliably.'
  },
  ElectroBall: {
    name: 'Electro Ball',
    type: 'Electric',
    power: 80,
    accuracy: 100,
    category: 'Special',
    description: 'Launches an electric orb at the enemy.'
  },
  Flamethrower: {
    name: 'Flamethrower',
    type: 'Fire',
    power: 90,
    accuracy: 100,
    category: 'Special',
    effect: 'burn',
    description: 'A devastating blast of fire. May burn the target.'
  },
  AirSlash: {
    name: 'Air Slash',
    type: 'Flying',
    power: 75,
    accuracy: 95,
    category: 'Special',
    description: 'A blade of wind that slices the opponent.'
  },
  DragonClaw: {
    name: 'Dragon Claw',
    type: 'Fire',
    power: 80,
    accuracy: 100,
    category: 'Physical',
    description: 'Slashes the foe with sharp draconic claws.'
  },
  FireSpin: {
    name: 'Fire Spin',
    type: 'Fire',
    power: 35,
    accuracy: 85,
    category: 'Special',
    effect: 'burn',
    description: 'Traps and burns the opponent in a fire vortex.'
  },
  HydroPump: {
    name: 'Hydro Pump',
    type: 'Water',
    power: 110,
    accuracy: 80,
    category: 'Special',
    description: 'Launches a high-pressure water blast.'
  },
  Surf: {
    name: 'Surf',
    type: 'Water',
    power: 90,
    accuracy: 100,
    category: 'Special',
    description: 'Summons a huge tidal wave to flood the target.'
  },
  SkullBash: {
    name: 'Skull Bash',
    type: 'Steel',
    power: 100,
    accuracy: 100,
    category: 'Physical',
    description: 'Charges up and bashes head-first.'
  },
  IceBeam: {
    name: 'Ice Beam',
    type: 'Water',
    power: 90,
    accuracy: 100,
    category: 'Special',
    description: 'Blasts a freezing ice beam at the target.'
  },
  Psychic: {
    name: 'Psychic',
    type: 'Psychic',
    power: 90,
    accuracy: 100,
    category: 'Special',
    description: 'A powerful telekinetic burst. Highly effective.'
  },
  ShadowBall: {
    name: 'Shadow Ball',
    type: 'Ghost',
    power: 80,
    accuracy: 100,
    category: 'Special',
    description: 'Hurls a dark, spooky shadowy orb.'
  },
  AuraSphere: {
    name: 'Aura Sphere',
    type: 'Fighting',
    power: 80,
    accuracy: 100,
    category: 'Special',
    description: 'An aura blast that never misses.'
  },
  Recover: {
    name: 'Recover',
    type: 'Psychic',
    power: 0,
    accuracy: 100,
    category: 'Status',
    effect: 'heal',
    description: 'Heals the user by 50% of their max HP.'
  },
  CloseCombat: {
    name: 'Close Combat',
    type: 'Fighting',
    power: 120,
    accuracy: 100,
    category: 'Physical',
    description: 'An all-out attack that inflicts massive damage.'
  },
  ExtremeSpeed: {
    name: 'Extreme Speed',
    type: 'Flying',
    power: 80,
    accuracy: 100,
    category: 'Physical',
    description: 'An blindingly fast charge strike.'
  },
  FlashCannon: {
    name: 'Flash Cannon',
    type: 'Steel',
    power: 80,
    accuracy: 100,
    category: 'Special',
    description: 'Unleashes a brilliant ray of steel light.'
  },
  SludgeBomb: {
    name: 'Sludge Bomb',
    type: 'Poison',
    power: 90,
    accuracy: 100,
    category: 'Special',
    description: 'Hurls a toxic bomb of sludge at the foe.'
  },
  DarkPulse: {
    name: 'Dark Pulse',
    type: 'Ghost',
    power: 80,
    accuracy: 100,
    category: 'Special',
    description: 'Releases a dark aura wave from the heart.'
  },
  DazzlingGleam: {
    name: 'Dazzling Gleam',
    type: 'Psychic',
    power: 80,
    accuracy: 100,
    category: 'Special',
    description: 'Emits a blinding light that damages the target.'
  },
  // EXPANSION MOVES:
  GigaDrain: {
    name: 'Giga Drain',
    type: 'Poison',
    power: 75,
    accuracy: 100,
    category: 'Special',
    effect: 'heal',
    description: 'Nutrient-draining attack. Restores user by 50% max HP.'
  },
  LeafStorm: {
    name: 'Leaf Storm',
    type: 'Poison',
    power: 130,
    accuracy: 90,
    category: 'Special',
    description: 'Whiplash storm of sharp leaves. Devastating power.'
  },
  DracoMeteor: {
    name: 'Draco Meteor',
    type: 'Fire',
    power: 130,
    accuracy: 90,
    category: 'Special',
    description: 'Summons comets from the sky to smash the opponent.'
  },
  Outrage: {
    name: 'Outrage',
    type: 'Fighting',
    power: 120,
    accuracy: 100,
    category: 'Physical',
    description: 'An all-out thrashing rage attack.'
  },
  Hurricane: {
    name: 'Hurricane',
    type: 'Flying',
    power: 110,
    accuracy: 70,
    category: 'Special',
    description: 'Summons a raging wind tunnel. Incredibly powerful.'
  },
  Moonblast: {
    name: 'Moonblast',
    type: 'Psychic',
    power: 95,
    accuracy: 100,
    category: 'Special',
    description: 'Launches a mysterious power of the moon.'
  },
  PlayRough: {
    name: 'Play Rough',
    type: 'Fighting',
    power: 90,
    accuracy: 90,
    category: 'Physical',
    description: 'Plays rough with the target, dealing high damage.'
  },
  SacredSword: {
    name: 'Sacred Sword',
    type: 'Fighting',
    power: 90,
    accuracy: 100,
    category: 'Physical',
    description: 'An elegant slash with a horn or sword.'
  },
  KingsShield: {
    name: 'Kings Shield',
    type: 'Steel',
    power: 0,
    accuracy: 100,
    category: 'Status',
    effect: 'heal',
    description: 'Tanks hits and restores HP using kingly power.'
  },
  ShadowClaw: {
    name: 'Shadow Claw',
    type: 'Ghost',
    power: 70,
    accuracy: 100,
    category: 'Physical',
    description: 'Slashes with sharp shadow-claws.'
  },
  MeteorMash: {
    name: 'Meteor Mash',
    type: 'Steel',
    power: 90,
    accuracy: 90,
    category: 'Physical',
    description: 'Fires a meteor-like punch at the opponent.'
  },
  HyperVoice: {
    name: 'Hyper Voice',
    type: 'Flying',
    power: 90,
    accuracy: 100,
    category: 'Special',
    description: 'Emits a loud sound wave that echoes around.'
  },
  BitterBlade: {
    name: 'Bitter Blade',
    type: 'Fire',
    power: 90,
    accuracy: 100,
    category: 'Physical',
    effect: 'heal',
    description: 'Absorbs bitter regrets to slice and heal HP.'
  }
};

export const POKEMON_ROSTER: Pokemon[] = [
  // --- KANTO (Gen 1) ---
  {
    id: 'poke_pikachu',
    name: 'Pikachu',
    type: ['Electric'],
    hp: 135,
    maxHp: 135,
    attack: 55,
    defense: 40,
    spAtk: 50,
    spDef: 50,
    speed: 90,
    moves: [MOVES_DATABASE.Thunderbolt, MOVES_DATABASE.IronTail, MOVES_DATABASE.QuickAttack, MOVES_DATABASE.ElectroBall],
    dexNumber: 25,
    region: 'Kanto'
  },
  {
    id: 'poke_charizard',
    name: 'Charizard',
    type: ['Fire', 'Flying'],
    hp: 178,
    maxHp: 178,
    attack: 84,
    defense: 78,
    spAtk: 109,
    spDef: 85,
    speed: 100,
    moves: [MOVES_DATABASE.Flamethrower, MOVES_DATABASE.AirSlash, MOVES_DATABASE.DragonClaw, MOVES_DATABASE.FireSpin],
    dexNumber: 6,
    region: 'Kanto'
  },
  {
    id: 'poke_blastoise',
    name: 'Blastoise',
    type: ['Water'],
    hp: 184,
    maxHp: 184,
    attack: 83,
    defense: 100,
    spAtk: 85,
    spDef: 105,
    speed: 78,
    moves: [MOVES_DATABASE.HydroPump, MOVES_DATABASE.Surf, MOVES_DATABASE.SkullBash, MOVES_DATABASE.IceBeam],
    dexNumber: 9,
    region: 'Kanto'
  },
  {
    id: 'poke_venusaur',
    name: 'Venusaur',
    type: ['Poison', 'Water'],
    hp: 180,
    maxHp: 180,
    attack: 82,
    defense: 83,
    spAtk: 100,
    spDef: 100,
    speed: 80,
    moves: [MOVES_DATABASE.LeafStorm, MOVES_DATABASE.SludgeBomb, MOVES_DATABASE.GigaDrain, MOVES_DATABASE.SkullBash],
    dexNumber: 3,
    region: 'Kanto'
  },
  {
    id: 'poke_eevee',
    name: 'Eevee',
    type: ['Psychic', 'Flying'],
    hp: 150,
    maxHp: 150,
    attack: 55,
    defense: 50,
    spAtk: 45,
    spDef: 65,
    speed: 55,
    moves: [MOVES_DATABASE.QuickAttack, MOVES_DATABASE.PlayRough, MOVES_DATABASE.IronTail, MOVES_DATABASE.Recover],
    dexNumber: 133,
    region: 'Kanto'
  },
  {
    id: 'poke_gengar',
    name: 'Gengar',
    type: ['Ghost', 'Poison'],
    hp: 160,
    maxHp: 160,
    attack: 65,
    defense: 60,
    spAtk: 130,
    spDef: 75,
    speed: 110,
    moves: [MOVES_DATABASE.ShadowBall, MOVES_DATABASE.SludgeBomb, MOVES_DATABASE.DarkPulse, MOVES_DATABASE.DazzlingGleam],
    dexNumber: 94,
    region: 'Kanto'
  },
  {
    id: 'poke_dragonite',
    name: 'Dragonite',
    type: ['Fire', 'Flying'],
    hp: 191,
    maxHp: 191,
    attack: 134,
    defense: 95,
    spAtk: 100,
    spDef: 100,
    speed: 80,
    moves: [MOVES_DATABASE.DracoMeteor, MOVES_DATABASE.Outrage, MOVES_DATABASE.ExtremeSpeed, MOVES_DATABASE.Flamethrower],
    dexNumber: 149,
    region: 'Kanto'
  },
  {
    id: 'poke_gyarados',
    name: 'Gyarados',
    type: ['Water', 'Flying'],
    hp: 195,
    maxHp: 195,
    attack: 125,
    defense: 79,
    spAtk: 60,
    spDef: 100,
    speed: 81,
    moves: [MOVES_DATABASE.HydroPump, MOVES_DATABASE.Outrage, MOVES_DATABASE.Hurricane, MOVES_DATABASE.Surf],
    dexNumber: 130,
    region: 'Kanto'
  },
  {
    id: 'poke_mewtwo',
    name: 'Mewtwo',
    type: ['Psychic'],
    hp: 206,
    maxHp: 206,
    attack: 110,
    defense: 90,
    spAtk: 154,
    spDef: 90,
    speed: 130,
    moves: [MOVES_DATABASE.Psychic, MOVES_DATABASE.ShadowBall, MOVES_DATABASE.AuraSphere, MOVES_DATABASE.Recover],
    dexNumber: 150,
    region: 'Kanto'
  },
  {
    id: 'poke_arcanine',
    name: 'Arcanine',
    type: ['Fire'],
    hp: 190,
    maxHp: 190,
    attack: 110,
    defense: 80,
    spAtk: 100,
    spDef: 80,
    speed: 95,
    moves: [MOVES_DATABASE.Flamethrower, MOVES_DATABASE.ExtremeSpeed, MOVES_DATABASE.Outrage, MOVES_DATABASE.FireSpin],
    dexNumber: 59,
    region: 'Kanto'
  },
  {
    id: 'poke_alakazam',
    name: 'Alakazam',
    type: ['Psychic'],
    hp: 155,
    maxHp: 155,
    attack: 50,
    defense: 45,
    spAtk: 135,
    spDef: 95,
    speed: 120,
    moves: [MOVES_DATABASE.Psychic, MOVES_DATABASE.ShadowBall, MOVES_DATABASE.DazzlingGleam, MOVES_DATABASE.Recover],
    dexNumber: 65,
    region: 'Kanto'
  },
  {
    id: 'poke_machamp',
    name: 'Machamp',
    type: ['Fighting'],
    hp: 190,
    maxHp: 190,
    attack: 130,
    defense: 80,
    spAtk: 65,
    spDef: 85,
    speed: 55,
    moves: [MOVES_DATABASE.CloseCombat, MOVES_DATABASE.AuraSphere, MOVES_DATABASE.PlayRough, MOVES_DATABASE.SkullBash],
    dexNumber: 68,
    region: 'Kanto'
  },
  {
    id: 'poke_snorlax',
    name: 'Snorlax',
    type: ['Normal'],
    hp: 260,
    maxHp: 260,
    attack: 110,
    defense: 65,
    spAtk: 65,
    spDef: 110,
    speed: 30,
    moves: [MOVES_DATABASE.SkullBash, MOVES_DATABASE.IceBeam, MOVES_DATABASE.IronTail, MOVES_DATABASE.Recover],
    dexNumber: 143,
    region: 'Kanto'
  },
  {
    id: 'poke_nidoking',
    name: 'Nidoking',
    type: ['Poison', 'Ground'],
    hp: 181,
    maxHp: 181,
    attack: 102,
    defense: 77,
    spAtk: 85,
    spDef: 75,
    speed: 85,
    moves: [MOVES_DATABASE.SludgeBomb, MOVES_DATABASE.Flamethrower, MOVES_DATABASE.IronTail, MOVES_DATABASE.SkullBash],
    dexNumber: 34,
    region: 'Kanto'
  },
  {
    id: 'poke_lapras',
    name: 'Lapras',
    type: ['Water', 'Ice'],
    hp: 230,
    maxHp: 230,
    attack: 85,
    defense: 80,
    spAtk: 85,
    spDef: 95,
    speed: 60,
    moves: [MOVES_DATABASE.HydroPump, MOVES_DATABASE.IceBeam, MOVES_DATABASE.Surf, MOVES_DATABASE.Recover],
    dexNumber: 131,
    region: 'Kanto'
  },
  {
    id: 'poke_jolteon',
    name: 'Jolteon',
    type: ['Electric'],
    hp: 165,
    maxHp: 165,
    attack: 65,
    defense: 60,
    spAtk: 110,
    spDef: 95,
    speed: 130,
    moves: [MOVES_DATABASE.Thunderbolt, MOVES_DATABASE.ElectroBall, MOVES_DATABASE.QuickAttack, MOVES_DATABASE.ShadowBall],
    dexNumber: 135,
    region: 'Kanto'
  },
  {
    id: 'poke_ninetales',
    name: 'Ninetales',
    type: ['Fire'],
    hp: 173,
    maxHp: 173,
    attack: 76,
    defense: 75,
    spAtk: 81,
    spDef: 100,
    speed: 100,
    moves: [MOVES_DATABASE.Flamethrower, MOVES_DATABASE.FireSpin, MOVES_DATABASE.DarkPulse, MOVES_DATABASE.DazzlingGleam],
    dexNumber: 38,
    region: 'Kanto'
  },
  {
    id: 'poke_scyther',
    name: 'Scyther',
    type: ['Bug', 'Flying'],
    hp: 170,
    maxHp: 170,
    attack: 110,
    defense: 80,
    spAtk: 55,
    spDef: 80,
    speed: 105,
    moves: [MOVES_DATABASE.AirSlash, MOVES_DATABASE.CloseCombat, MOVES_DATABASE.QuickAttack, MOVES_DATABASE.SacredSword],
    dexNumber: 123,
    region: 'Kanto'
  },
  {
    id: 'poke_aerodactyl',
    name: 'Aerodactyl',
    type: ['Rock', 'Flying'],
    hp: 180,
    maxHp: 180,
    attack: 105,
    defense: 65,
    spAtk: 60,
    spDef: 75,
    speed: 130,
    moves: [MOVES_DATABASE.AirSlash, MOVES_DATABASE.DragonClaw, MOVES_DATABASE.QuickAttack, MOVES_DATABASE.Hurricane],
    dexNumber: 142,
    region: 'Kanto'
  },
  {
    id: 'poke_vaporeon',
    name: 'Vaporeon',
    type: ['Water'],
    hp: 230,
    maxHp: 230,
    attack: 65,
    defense: 60,
    spAtk: 110,
    spDef: 95,
    speed: 65,
    moves: [MOVES_DATABASE.HydroPump, MOVES_DATABASE.Surf, MOVES_DATABASE.IceBeam, MOVES_DATABASE.Recover],
    dexNumber: 134,
    region: 'Kanto'
  },
  {
    id: 'poke_flareon',
    name: 'Flareon',
    type: ['Fire'],
    hp: 165,
    maxHp: 165,
    attack: 130,
    defense: 60,
    spAtk: 95,
    spDef: 110,
    speed: 65,
    moves: [MOVES_DATABASE.Flamethrower, MOVES_DATABASE.FireSpin, MOVES_DATABASE.QuickAttack, MOVES_DATABASE.Outrage],
    dexNumber: 136,
    region: 'Kanto'
  },
  {
    id: 'poke_golem',
    name: 'Golem',
    type: ['Rock', 'Ground'],
    hp: 180,
    maxHp: 180,
    attack: 120,
    defense: 130,
    spAtk: 55,
    spDef: 65,
    speed: 45,
    moves: [MOVES_DATABASE.SkullBash, MOVES_DATABASE.IronTail, MOVES_DATABASE.CloseCombat, MOVES_DATABASE.FireSpin],
    dexNumber: 76,
    region: 'Kanto'
  },

  // --- JOHTO (Gen 2) ---
  {
    id: 'poke_umbreon',
    name: 'Umbreon',
    type: ['Ghost'],
    hp: 195,
    maxHp: 195,
    attack: 65,
    defense: 110,
    spAtk: 60,
    spDef: 130,
    speed: 65,
    moves: [MOVES_DATABASE.DarkPulse, MOVES_DATABASE.ShadowBall, MOVES_DATABASE.Recover, MOVES_DATABASE.QuickAttack],
    dexNumber: 197,
    region: 'Johto'
  },
  {
    id: 'poke_scizor',
    name: 'Scizor',
    type: ['Steel', 'Fighting'],
    hp: 170,
    maxHp: 170,
    attack: 130,
    defense: 100,
    spAtk: 55,
    spDef: 80,
    speed: 65,
    moves: [MOVES_DATABASE.IronTail, MOVES_DATABASE.CloseCombat, MOVES_DATABASE.SkullBash, MOVES_DATABASE.QuickAttack],
    dexNumber: 212,
    region: 'Johto'
  },
  {
    id: 'poke_tyranitar',
    name: 'Tyranitar',
    type: ['Steel', 'Fighting'],
    hp: 200,
    maxHp: 200,
    attack: 134,
    defense: 110,
    spAtk: 95,
    spDef: 100,
    speed: 61,
    moves: [MOVES_DATABASE.Outrage, MOVES_DATABASE.IronTail, MOVES_DATABASE.DarkPulse, MOVES_DATABASE.SkullBash],
    dexNumber: 248,
    region: 'Johto'
  },
  {
    id: 'poke_lugia',
    name: 'Lugia',
    type: ['Psychic', 'Flying'],
    hp: 206,
    maxHp: 206,
    attack: 90,
    defense: 130,
    spAtk: 90,
    spDef: 154,
    speed: 110,
    moves: [MOVES_DATABASE.Psychic, MOVES_DATABASE.Hurricane, MOVES_DATABASE.IceBeam, MOVES_DATABASE.Recover],
    dexNumber: 249,
    region: 'Johto'
  },
  {
    id: 'poke_typhlosion',
    name: 'Typhlosion',
    type: ['Fire'],
    hp: 178,
    maxHp: 178,
    attack: 84,
    defense: 78,
    spAtk: 109,
    spDef: 85,
    speed: 100,
    moves: [MOVES_DATABASE.Flamethrower, MOVES_DATABASE.FireSpin, MOVES_DATABASE.QuickAttack, MOVES_DATABASE.Outrage],
    dexNumber: 157,
    region: 'Johto'
  },
  {
    id: 'poke_feraligatr',
    name: 'Feraligatr',
    type: ['Water'],
    hp: 185,
    maxHp: 185,
    attack: 105,
    defense: 100,
    spAtk: 79,
    spDef: 83,
    speed: 78,
    moves: [MOVES_DATABASE.HydroPump, MOVES_DATABASE.Surf, MOVES_DATABASE.SkullBash, MOVES_DATABASE.IceBeam],
    dexNumber: 160,
    region: 'Johto'
  },
  {
    id: 'poke_ampharos',
    name: 'Ampharos',
    type: ['Electric'],
    hp: 190,
    maxHp: 190,
    attack: 75,
    defense: 85,
    spAtk: 115,
    spDef: 90,
    speed: 55,
    moves: [MOVES_DATABASE.Thunderbolt, MOVES_DATABASE.ElectroBall, MOVES_DATABASE.DazzlingGleam, MOVES_DATABASE.Recover],
    dexNumber: 181,
    region: 'Johto'
  },
  {
    id: 'poke_heracross',
    name: 'Heracross',
    type: ['Fighting'],
    hp: 180,
    maxHp: 180,
    attack: 125,
    defense: 75,
    spAtk: 40,
    spDef: 95,
    speed: 85,
    moves: [MOVES_DATABASE.CloseCombat, MOVES_DATABASE.AuraSphere, MOVES_DATABASE.QuickAttack, MOVES_DATABASE.SkullBash],
    dexNumber: 214,
    region: 'Johto'
  },
  {
    id: 'poke_meganium',
    name: 'Meganium',
    type: ['Grass'],
    hp: 180,
    maxHp: 180,
    attack: 82,
    defense: 100,
    spAtk: 83,
    spDef: 100,
    speed: 80,
    moves: [MOVES_DATABASE.LeafStorm, MOVES_DATABASE.GigaDrain, MOVES_DATABASE.Recover, MOVES_DATABASE.DazzlingGleam],
    dexNumber: 154,
    region: 'Johto'
  },
  {
    id: 'poke_espeon',
    name: 'Espeon',
    type: ['Psychic'],
    hp: 165,
    maxHp: 165,
    attack: 65,
    defense: 60,
    spAtk: 130,
    spDef: 95,
    speed: 110,
    moves: [MOVES_DATABASE.Psychic, MOVES_DATABASE.ShadowBall, MOVES_DATABASE.DazzlingGleam, MOVES_DATABASE.Recover],
    dexNumber: 196,
    region: 'Johto'
  },
  {
    id: 'poke_crobat',
    name: 'Crobat',
    type: ['Poison', 'Flying'],
    hp: 185,
    maxHp: 185,
    attack: 90,
    defense: 80,
    spAtk: 70,
    spDef: 80,
    speed: 130,
    moves: [MOVES_DATABASE.AirSlash, MOVES_DATABASE.SludgeBomb, MOVES_DATABASE.Hurricane, MOVES_DATABASE.QuickAttack],
    dexNumber: 169,
    region: 'Johto'
  },
  {
    id: 'poke_steelix',
    name: 'Steelix',
    type: ['Steel', 'Ground'],
    hp: 175,
    maxHp: 175,
    attack: 85,
    defense: 200,
    spAtk: 55,
    spDef: 65,
    speed: 30,
    moves: [MOVES_DATABASE.IronTail, MOVES_DATABASE.SkullBash, MOVES_DATABASE.FlashCannon, MOVES_DATABASE.DarkPulse],
    dexNumber: 208,
    region: 'Johto'
  },
  {
    id: 'poke_skarmory',
    name: 'Skarmory',
    type: ['Steel', 'Flying'],
    hp: 165,
    maxHp: 165,
    attack: 80,
    defense: 140,
    spAtk: 40,
    spDef: 70,
    speed: 70,
    moves: [MOVES_DATABASE.AirSlash, MOVES_DATABASE.IronTail, MOVES_DATABASE.FlashCannon, MOVES_DATABASE.Recover],
    dexNumber: 227,
    region: 'Johto'
  },
  {
    id: 'poke_kingdra',
    name: 'Kingdra',
    type: ['Water', 'Dragon'],
    hp: 175,
    maxHp: 175,
    attack: 95,
    defense: 95,
    spAtk: 95,
    spDef: 95,
    speed: 85,
    moves: [MOVES_DATABASE.HydroPump, MOVES_DATABASE.DracoMeteor, MOVES_DATABASE.IceBeam, MOVES_DATABASE.Surf],
    dexNumber: 230,
    region: 'Johto'
  },
  {
    id: 'poke_donphan',
    name: 'Donphan',
    type: ['Ground'],
    hp: 190,
    maxHp: 190,
    attack: 120,
    defense: 120,
    spAtk: 60,
    spDef: 60,
    speed: 50,
    moves: [MOVES_DATABASE.SkullBash, MOVES_DATABASE.IronTail, MOVES_DATABASE.CloseCombat, MOVES_DATABASE.PlayRough],
    dexNumber: 232,
    region: 'Johto'
  },
  {
    id: 'poke_raikou',
    name: 'Raikou',
    type: ['Electric'],
    hp: 190,
    maxHp: 190,
    attack: 85,
    defense: 75,
    spAtk: 115,
    spDef: 100,
    speed: 115,
    moves: [MOVES_DATABASE.Thunderbolt, MOVES_DATABASE.ElectroBall, MOVES_DATABASE.ExtremeSpeed, MOVES_DATABASE.ShadowBall],
    dexNumber: 243,
    region: 'Johto'
  },
  {
    id: 'poke_entei',
    name: 'Entei',
    type: ['Fire'],
    hp: 215,
    maxHp: 215,
    attack: 115,
    defense: 85,
    spAtk: 90,
    spDef: 75,
    speed: 100,
    moves: [MOVES_DATABASE.Flamethrower, MOVES_DATABASE.FireSpin, MOVES_DATABASE.ExtremeSpeed, MOVES_DATABASE.IronTail],
    dexNumber: 244,
    region: 'Johto'
  },
  {
    id: 'poke_suicune',
    name: 'Suicune',
    type: ['Water'],
    hp: 200,
    maxHp: 200,
    attack: 75,
    defense: 115,
    spAtk: 90,
    spDef: 115,
    speed: 85,
    moves: [MOVES_DATABASE.HydroPump, MOVES_DATABASE.IceBeam, MOVES_DATABASE.Surf, MOVES_DATABASE.Recover],
    dexNumber: 245,
    region: 'Johto'
  },

  // --- HOENN (Gen 3) ---
  {
    id: 'poke_sceptile',
    name: 'Sceptile',
    type: ['Flying', 'Poison'],
    hp: 170,
    maxHp: 170,
    attack: 85,
    defense: 65,
    spAtk: 105,
    spDef: 85,
    speed: 120,
    moves: [MOVES_DATABASE.LeafStorm, MOVES_DATABASE.GigaDrain, MOVES_DATABASE.QuickAttack, MOVES_DATABASE.AirSlash],
    dexNumber: 254,
    region: 'Hoenn'
  },
  {
    id: 'poke_gardevoir',
    name: 'Gardevoir',
    type: ['Psychic'],
    hp: 168,
    maxHp: 168,
    attack: 65,
    defense: 65,
    spAtk: 125,
    spDef: 115,
    speed: 80,
    moves: [MOVES_DATABASE.Psychic, MOVES_DATABASE.Moonblast, MOVES_DATABASE.DazzlingGleam, MOVES_DATABASE.ShadowBall],
    dexNumber: 282,
    region: 'Hoenn'
  },
  {
    id: 'poke_kyogre',
    name: 'Kyogre',
    type: ['Water'],
    hp: 200,
    maxHp: 200,
    attack: 100,
    defense: 90,
    spAtk: 150,
    spDef: 140,
    speed: 90,
    moves: [MOVES_DATABASE.HydroPump, MOVES_DATABASE.Surf, MOVES_DATABASE.IceBeam, MOVES_DATABASE.Thunderbolt],
    dexNumber: 382,
    region: 'Hoenn'
  },
  {
    id: 'poke_groudon',
    name: 'Groudon',
    type: ['Fire', 'Fighting'],
    hp: 200,
    maxHp: 200,
    attack: 150,
    defense: 140,
    spAtk: 100,
    spDef: 90,
    speed: 90,
    moves: [MOVES_DATABASE.Flamethrower, MOVES_DATABASE.FireSpin, MOVES_DATABASE.SkullBash, MOVES_DATABASE.Recover],
    dexNumber: 383,
    region: 'Hoenn'
  },
  {
    id: 'poke_rayquaza',
    name: 'Rayquaza',
    type: ['Flying', 'Fire'],
    hp: 210,
    maxHp: 210,
    attack: 150,
    defense: 90,
    spAtk: 150,
    spDef: 90,
    speed: 115,
    moves: [MOVES_DATABASE.DracoMeteor, MOVES_DATABASE.Hurricane, MOVES_DATABASE.ExtremeSpeed, MOVES_DATABASE.Outrage],
    dexNumber: 384,
    region: 'Hoenn'
  },
  {
    id: 'poke_blaziken',
    name: 'Blaziken',
    type: ['Fire', 'Fighting'],
    hp: 180,
    maxHp: 180,
    attack: 120,
    defense: 70,
    spAtk: 110,
    spDef: 70,
    speed: 80,
    moves: [MOVES_DATABASE.Flamethrower, MOVES_DATABASE.CloseCombat, MOVES_DATABASE.FireSpin, MOVES_DATABASE.AuraSphere],
    dexNumber: 257,
    region: 'Hoenn'
  },
  {
    id: 'poke_swampert',
    name: 'Swampert',
    type: ['Water', 'Poison'],
    hp: 200,
    maxHp: 200,
    attack: 110,
    defense: 90,
    spAtk: 85,
    spDef: 90,
    speed: 60,
    moves: [MOVES_DATABASE.HydroPump, MOVES_DATABASE.Surf, MOVES_DATABASE.SludgeBomb, MOVES_DATABASE.SkullBash],
    dexNumber: 260,
    region: 'Hoenn'
  },
  {
    id: 'poke_metagross',
    name: 'Metagross',
    type: ['Steel', 'Psychic'],
    hp: 180,
    maxHp: 180,
    attack: 135,
    defense: 130,
    spAtk: 95,
    spDef: 90,
    speed: 70,
    moves: [MOVES_DATABASE.MeteorMash, MOVES_DATABASE.FlashCannon, MOVES_DATABASE.Psychic, MOVES_DATABASE.ShadowBall],
    dexNumber: 376,
    region: 'Hoenn'
  },
  {
    id: 'poke_salamence',
    name: 'Salamence',
    type: ['Dragon', 'Flying'],
    hp: 195,
    maxHp: 195,
    attack: 135,
    defense: 80,
    spAtk: 110,
    spDef: 80,
    speed: 100,
    moves: [MOVES_DATABASE.DracoMeteor, MOVES_DATABASE.Hurricane, MOVES_DATABASE.Flamethrower, MOVES_DATABASE.DragonClaw],
    dexNumber: 373,
    region: 'Hoenn'
  },
  {
    id: 'poke_flygon',
    name: 'Flygon',
    type: ['Dragon', 'Ground'],
    hp: 180,
    maxHp: 180,
    attack: 100,
    defense: 80,
    spAtk: 80,
    spDef: 80,
    speed: 100,
    moves: [MOVES_DATABASE.DracoMeteor, MOVES_DATABASE.DragonClaw, MOVES_DATABASE.Flamethrower, MOVES_DATABASE.SkullBash],
    dexNumber: 330,
    region: 'Hoenn'
  },
  {
    id: 'poke_aggron',
    name: 'Aggron',
    type: ['Steel', 'Rock'],
    hp: 170,
    maxHp: 170,
    attack: 110,
    defense: 180,
    spAtk: 60,
    spDef: 60,
    speed: 50,
    moves: [MOVES_DATABASE.IronTail, MOVES_DATABASE.SkullBash, MOVES_DATABASE.FlashCannon, MOVES_DATABASE.CloseCombat],
    dexNumber: 306,
    region: 'Hoenn'
  },
  {
    id: 'poke_milotic',
    name: 'Milotic',
    type: ['Water'],
    hp: 195,
    maxHp: 195,
    attack: 60,
    defense: 79,
    spAtk: 100,
    spDef: 125,
    speed: 81,
    moves: [MOVES_DATABASE.HydroPump, MOVES_DATABASE.IceBeam, MOVES_DATABASE.Surf, MOVES_DATABASE.Recover],
    dexNumber: 350,
    region: 'Hoenn'
  },
  {
    id: 'poke_absol',
    name: 'Absol',
    type: ['Dark'],
    hp: 165,
    maxHp: 165,
    attack: 130,
    defense: 60,
    spAtk: 75,
    spDef: 60,
    speed: 75,
    moves: [MOVES_DATABASE.DarkPulse, MOVES_DATABASE.ShadowClaw, MOVES_DATABASE.PlayRough, MOVES_DATABASE.QuickAttack],
    dexNumber: 359,
    region: 'Hoenn'
  },
  {
    id: 'poke_breloom',
    name: 'Breloom',
    type: ['Grass', 'Fighting'],
    hp: 160,
    maxHp: 160,
    attack: 130,
    defense: 80,
    spAtk: 60,
    spDef: 60,
    speed: 70,
    moves: [MOVES_DATABASE.LeafStorm, MOVES_DATABASE.CloseCombat, MOVES_DATABASE.GigaDrain, MOVES_DATABASE.SkullBash],
    dexNumber: 286,
    region: 'Hoenn'
  },
  {
    id: 'poke_slaking',
    name: 'Slaking',
    type: ['Normal'],
    hp: 250,
    maxHp: 250,
    attack: 160,
    defense: 100,
    spAtk: 95,
    spDef: 65,
    speed: 100,
    moves: [MOVES_DATABASE.SkullBash, MOVES_DATABASE.PlayRough, MOVES_DATABASE.ShadowBall, MOVES_DATABASE.Recover],
    dexNumber: 289,
    region: 'Hoenn'
  },
  {
    id: 'poke_walrein',
    name: 'Walrein',
    type: ['Ice', 'Water'],
    hp: 210,
    maxHp: 210,
    attack: 80,
    defense: 90,
    spAtk: 95,
    spDef: 90,
    speed: 65,
    moves: [MOVES_DATABASE.IceBeam, MOVES_DATABASE.HydroPump, MOVES_DATABASE.Surf, MOVES_DATABASE.Recover],
    dexNumber: 365,
    region: 'Hoenn'
  },
  {
    id: 'poke_ludicolo',
    name: 'Ludicolo',
    type: ['Water', 'Grass'],
    hp: 180,
    maxHp: 180,
    attack: 70,
    defense: 70,
    spAtk: 90,
    spDef: 100,
    speed: 70,
    moves: [MOVES_DATABASE.HydroPump, MOVES_DATABASE.LeafStorm, MOVES_DATABASE.GigaDrain, MOVES_DATABASE.Surf],
    dexNumber: 272,
    region: 'Hoenn'
  },
  {
    id: 'poke_altaria',
    name: 'Altaria',
    type: ['Dragon', 'Flying'],
    hp: 175,
    maxHp: 175,
    attack: 70,
    defense: 90,
    spAtk: 70,
    spDef: 105,
    speed: 80,
    moves: [MOVES_DATABASE.DracoMeteor, MOVES_DATABASE.Hurricane, MOVES_DATABASE.Moonblast, MOVES_DATABASE.Recover],
    dexNumber: 334,
    region: 'Hoenn'
  },

  // --- SINNOH (Gen 4) ---
  {
    id: 'poke_lucario',
    name: 'Lucario',
    type: ['Fighting', 'Steel'],
    hp: 170,
    maxHp: 170,
    attack: 110,
    defense: 70,
    spAtk: 115,
    spDef: 70,
    speed: 90,
    moves: [MOVES_DATABASE.AuraSphere, MOVES_DATABASE.CloseCombat, MOVES_DATABASE.ExtremeSpeed, MOVES_DATABASE.FlashCannon],
    dexNumber: 448,
    region: 'Sinnoh'
  },
  {
    id: 'poke_garchomp',
    name: 'Garchomp',
    type: ['Fighting', 'Fire'],
    hp: 208,
    maxHp: 208,
    attack: 130,
    defense: 95,
    spAtk: 80,
    spDef: 85,
    speed: 102,
    moves: [MOVES_DATABASE.Outrage, MOVES_DATABASE.DragonClaw, MOVES_DATABASE.DracoMeteor, MOVES_DATABASE.SkullBash],
    dexNumber: 445,
    region: 'Sinnoh'
  },
  {
    id: 'poke_togekiss',
    name: 'Togekiss',
    type: ['Flying', 'Psychic'],
    hp: 185,
    maxHp: 185,
    attack: 50,
    defense: 95,
    spAtk: 120,
    spDef: 115,
    speed: 80,
    moves: [MOVES_DATABASE.AirSlash, MOVES_DATABASE.Moonblast, MOVES_DATABASE.DazzlingGleam, MOVES_DATABASE.Recover],
    dexNumber: 468,
    region: 'Sinnoh'
  },
  {
    id: 'poke_infernape',
    name: 'Infernape',
    type: ['Fire', 'Fighting'],
    hp: 176,
    maxHp: 176,
    attack: 104,
    defense: 71,
    spAtk: 104,
    spDef: 71,
    speed: 108,
    moves: [MOVES_DATABASE.Flamethrower, MOVES_DATABASE.CloseCombat, MOVES_DATABASE.FireSpin, MOVES_DATABASE.QuickAttack],
    dexNumber: 392,
    region: 'Sinnoh'
  },
  {
    id: 'poke_empoleon',
    name: 'Empoleon',
    type: ['Water', 'Steel'],
    hp: 184,
    maxHp: 184,
    attack: 86,
    defense: 88,
    spAtk: 111,
    spDef: 101,
    speed: 60,
    moves: [MOVES_DATABASE.HydroPump, MOVES_DATABASE.FlashCannon, MOVES_DATABASE.IceBeam, MOVES_DATABASE.Surf],
    dexNumber: 395,
    region: 'Sinnoh'
  },
  {
    id: 'poke_luxray',
    name: 'Luxray',
    type: ['Electric'],
    hp: 180,
    maxHp: 180,
    attack: 120,
    defense: 79,
    spAtk: 95,
    spDef: 79,
    speed: 70,
    moves: [MOVES_DATABASE.Thunderbolt, MOVES_DATABASE.IronTail, MOVES_DATABASE.QuickAttack, MOVES_DATABASE.ElectroBall],
    dexNumber: 405,
    region: 'Sinnoh'
  },
  {
    id: 'poke_torterra',
    name: 'Torterra',
    type: ['Grass', 'Ground'],
    hp: 195,
    maxHp: 195,
    attack: 109,
    defense: 105,
    spAtk: 75,
    spDef: 85,
    speed: 56,
    moves: [MOVES_DATABASE.LeafStorm, MOVES_DATABASE.SkullBash, MOVES_DATABASE.GigaDrain, MOVES_DATABASE.IronTail],
    dexNumber: 389,
    region: 'Sinnoh'
  },
  {
    id: 'poke_staraptor',
    name: 'Staraptor',
    type: ['Normal', 'Flying'],
    hp: 185,
    maxHp: 185,
    attack: 120,
    defense: 70,
    spAtk: 50,
    spDef: 60,
    speed: 100,
    moves: [MOVES_DATABASE.AirSlash, MOVES_DATABASE.CloseCombat, MOVES_DATABASE.QuickAttack, MOVES_DATABASE.Hurricane],
    dexNumber: 398,
    region: 'Sinnoh'
  },
  {
    id: 'poke_roserade',
    name: 'Roserade',
    type: ['Grass', 'Poison'],
    hp: 160,
    maxHp: 160,
    attack: 70,
    defense: 65,
    spAtk: 125,
    spDef: 105,
    speed: 90,
    moves: [MOVES_DATABASE.LeafStorm, MOVES_DATABASE.SludgeBomb, MOVES_DATABASE.GigaDrain, MOVES_DATABASE.DazzlingGleam],
    dexNumber: 407,
    region: 'Sinnoh'
  },
  {
    id: 'poke_electivire',
    name: 'Electivire',
    type: ['Electric'],
    hp: 175,
    maxHp: 175,
    attack: 123,
    defense: 67,
    spAtk: 95,
    spDef: 85,
    speed: 95,
    moves: [MOVES_DATABASE.Thunderbolt, MOVES_DATABASE.IronTail, MOVES_DATABASE.ElectroBall, MOVES_DATABASE.CloseCombat],
    dexNumber: 466,
    region: 'Sinnoh'
  },
  {
    id: 'poke_magmortar',
    name: 'Magmortar',
    type: ['Fire'],
    hp: 175,
    maxHp: 175,
    attack: 95,
    defense: 67,
    spAtk: 125,
    spDef: 95,
    speed: 83,
    moves: [MOVES_DATABASE.Flamethrower, MOVES_DATABASE.FireSpin, MOVES_DATABASE.Psychic, MOVES_DATABASE.SludgeBomb],
    dexNumber: 467,
    region: 'Sinnoh'
  },
  {
    id: 'poke_glaceon',
    name: 'Glaceon',
    type: ['Ice'],
    hp: 165,
    maxHp: 165,
    attack: 60,
    defense: 110,
    spAtk: 130,
    spDef: 95,
    speed: 65,
    moves: [MOVES_DATABASE.IceBeam, MOVES_DATABASE.ShadowBall, MOVES_DATABASE.HydroPump, MOVES_DATABASE.Recover],
    dexNumber: 471,
    region: 'Sinnoh'
  },
  {
    id: 'poke_leafeon',
    name: 'Leafeon',
    type: ['Grass'],
    hp: 165,
    maxHp: 165,
    attack: 110,
    defense: 130,
    spAtk: 60,
    spDef: 65,
    speed: 95,
    moves: [MOVES_DATABASE.LeafStorm, MOVES_DATABASE.GigaDrain, MOVES_DATABASE.PlayRough, MOVES_DATABASE.QuickAttack],
    dexNumber: 470,
    region: 'Sinnoh'
  },
  {
    id: 'poke_gallade',
    name: 'Gallade',
    type: ['Psychic', 'Fighting'],
    hp: 168,
    maxHp: 168,
    attack: 125,
    defense: 65,
    spAtk: 65,
    spDef: 115,
    speed: 80,
    moves: [MOVES_DATABASE.Psychic, MOVES_DATABASE.CloseCombat, MOVES_DATABASE.SacredSword, MOVES_DATABASE.PlayRough],
    dexNumber: 475,
    region: 'Sinnoh'
  },
  {
    id: 'poke_dusknoir',
    name: 'Dusknoir',
    type: ['Ghost'],
    hp: 150,
    maxHp: 150,
    attack: 100,
    defense: 135,
    spAtk: 65,
    spDef: 135,
    speed: 45,
    moves: [MOVES_DATABASE.ShadowBall, MOVES_DATABASE.ShadowClaw, MOVES_DATABASE.DarkPulse, MOVES_DATABASE.Recover],
    dexNumber: 477,
    region: 'Sinnoh'
  },
  {
    id: 'poke_porygonz',
    name: 'Porygon-Z',
    type: ['Normal'],
    hp: 175,
    maxHp: 175,
    attack: 80,
    defense: 70,
    spAtk: 135,
    spDef: 75,
    speed: 90,
    moves: [MOVES_DATABASE.Thunderbolt, MOVES_DATABASE.IceBeam, MOVES_DATABASE.Psychic, MOVES_DATABASE.Recover],
    dexNumber: 474,
    region: 'Sinnoh'
  },

  // --- UNOVA (Gen 5) ---
  {
    id: 'poke_serperior',
    name: 'Serperior',
    type: ['Poison'],
    hp: 175,
    maxHp: 175,
    attack: 75,
    defense: 95,
    spAtk: 75,
    spDef: 95,
    speed: 113,
    moves: [MOVES_DATABASE.LeafStorm, MOVES_DATABASE.GigaDrain, MOVES_DATABASE.QuickAttack, MOVES_DATABASE.Recover],
    dexNumber: 497,
    region: 'Unova'
  },
  {
    id: 'poke_samurott',
    name: 'Samurott',
    type: ['Water'],
    hp: 195,
    maxHp: 195,
    attack: 100,
    defense: 85,
    spAtk: 108,
    spDef: 70,
    speed: 70,
    moves: [MOVES_DATABASE.HydroPump, MOVES_DATABASE.Surf, MOVES_DATABASE.IceBeam, MOVES_DATABASE.AirSlash],
    dexNumber: 503,
    region: 'Unova'
  },
  {
    id: 'poke_zoroark',
    name: 'Zoroark',
    type: ['Ghost'],
    hp: 160,
    maxHp: 160,
    attack: 105,
    defense: 60,
    spAtk: 120,
    spDef: 60,
    speed: 105,
    moves: [MOVES_DATABASE.DarkPulse, MOVES_DATABASE.ShadowBall, MOVES_DATABASE.ShadowClaw, MOVES_DATABASE.Flamethrower],
    dexNumber: 571,
    region: 'Unova'
  },
  {
    id: 'poke_hydreigon',
    name: 'Hydreigon',
    type: ['Fire', 'Flying'],
    hp: 192,
    maxHp: 192,
    attack: 105,
    defense: 90,
    spAtk: 125,
    spDef: 90,
    speed: 98,
    moves: [MOVES_DATABASE.DracoMeteor, MOVES_DATABASE.DarkPulse, MOVES_DATABASE.Flamethrower, MOVES_DATABASE.Hurricane],
    dexNumber: 635,
    region: 'Unova'
  },
  {
    id: 'poke_emboar',
    name: 'Emboar',
    type: ['Fire', 'Fighting'],
    hp: 210,
    maxHp: 210,
    attack: 123,
    defense: 65,
    spAtk: 100,
    spDef: 65,
    speed: 65,
    moves: [MOVES_DATABASE.Flamethrower, MOVES_DATABASE.CloseCombat, MOVES_DATABASE.FireSpin, MOVES_DATABASE.SkullBash],
    dexNumber: 500,
    region: 'Unova'
  },
  {
    id: 'poke_haxorus',
    name: 'Haxorus',
    type: ['Dragon'],
    hp: 176,
    maxHp: 176,
    attack: 147,
    defense: 90,
    spAtk: 60,
    spDef: 70,
    speed: 97,
    moves: [MOVES_DATABASE.DracoMeteor, MOVES_DATABASE.DragonClaw, MOVES_DATABASE.Outrage, MOVES_DATABASE.IronTail],
    dexNumber: 612,
    region: 'Unova'
  },
  {
    id: 'poke_krookodile',
    name: 'Krookodile',
    type: ['Ground', 'Dark'],
    hp: 195,
    maxHp: 195,
    attack: 117,
    defense: 80,
    spAtk: 65,
    spDef: 70,
    speed: 92,
    moves: [MOVES_DATABASE.DarkPulse, MOVES_DATABASE.SkullBash, MOVES_DATABASE.CloseCombat, MOVES_DATABASE.Outrage],
    dexNumber: 553,
    region: 'Unova'
  },
  {
    id: 'poke_chandelure',
    name: 'Chandelure',
    type: ['Fire', 'Ghost'],
    hp: 160,
    maxHp: 160,
    attack: 55,
    defense: 90,
    spAtk: 145,
    spDef: 90,
    speed: 80,
    moves: [MOVES_DATABASE.Flamethrower, MOVES_DATABASE.ShadowBall, MOVES_DATABASE.FireSpin, MOVES_DATABASE.DarkPulse],
    dexNumber: 609,
    region: 'Unova'
  },
  {
    id: 'poke_volcarona',
    name: 'Volcarona',
    type: ['Fire', 'Bug'],
    hp: 185,
    maxHp: 185,
    attack: 60,
    defense: 65,
    spAtk: 135,
    spDef: 105,
    speed: 100,
    moves: [MOVES_DATABASE.Flamethrower, MOVES_DATABASE.Hurricane, MOVES_DATABASE.FireSpin, MOVES_DATABASE.GigaDrain],
    dexNumber: 637,
    region: 'Unova'
  },
  {
    id: 'poke_reuniclus',
    name: 'Reuniclus',
    type: ['Psychic'],
    hp: 210,
    maxHp: 210,
    attack: 65,
    defense: 75,
    spAtk: 125,
    spDef: 85,
    speed: 30,
    moves: [MOVES_DATABASE.Psychic, MOVES_DATABASE.ShadowBall, MOVES_DATABASE.Recover, MOVES_DATABASE.DazzlingGleam],
    dexNumber: 579,
    region: 'Unova'
  },
  {
    id: 'poke_bisharp',
    name: 'Bisharp',
    type: ['Dark', 'Steel'],
    hp: 165,
    maxHp: 165,
    attack: 125,
    defense: 100,
    spAtk: 60,
    spDef: 70,
    speed: 70,
    moves: [MOVES_DATABASE.IronTail, MOVES_DATABASE.DarkPulse, MOVES_DATABASE.ShadowClaw, MOVES_DATABASE.FlashCannon],
    dexNumber: 625,
    region: 'Unova'
  },
  {
    id: 'poke_gigalith',
    name: 'Gigalith',
    type: ['Rock'],
    hp: 185,
    maxHp: 185,
    attack: 135,
    defense: 130,
    spAtk: 60,
    spDef: 80,
    speed: 25,
    moves: [MOVES_DATABASE.SkullBash, MOVES_DATABASE.IronTail, MOVES_DATABASE.FlashCannon, MOVES_DATABASE.CloseCombat],
    dexNumber: 526,
    region: 'Unova'
  },
  {
    id: 'poke_mienshao',
    name: 'Mienshao',
    type: ['Fighting'],
    hp: 165,
    maxHp: 165,
    attack: 125,
    defense: 60,
    spAtk: 95,
    spDef: 60,
    speed: 105,
    moves: [MOVES_DATABASE.CloseCombat, MOVES_DATABASE.AuraSphere, MOVES_DATABASE.QuickAttack, MOVES_DATABASE.Recover],
    dexNumber: 620,
    region: 'Unova'
  },
  {
    id: 'poke_galvantula',
    name: 'Galvantula',
    type: ['Bug', 'Electric'],
    hp: 170,
    maxHp: 170,
    attack: 77,
    defense: 60,
    spAtk: 97,
    spDef: 60,
    speed: 108,
    moves: [MOVES_DATABASE.Thunderbolt, MOVES_DATABASE.ElectroBall, MOVES_DATABASE.GigaDrain, MOVES_DATABASE.AirSlash],
    dexNumber: 596,
    region: 'Unova'
  },

  // --- KALOS (Gen 6) ---
  {
    id: 'poke_greninja',
    name: 'Greninja',
    type: ['Water', 'Ghost'],
    hp: 172,
    maxHp: 172,
    attack: 95,
    defense: 67,
    spAtk: 103,
    spDef: 71,
    speed: 122,
    moves: [MOVES_DATABASE.HydroPump, MOVES_DATABASE.DarkPulse, MOVES_DATABASE.ShadowBall, MOVES_DATABASE.QuickAttack],
    dexNumber: 658,
    region: 'Kalos'
  },
  {
    id: 'poke_sylveon',
    name: 'Sylveon',
    type: ['Psychic'],
    hp: 195,
    maxHp: 195,
    attack: 65,
    defense: 65,
    spAtk: 110,
    spDef: 130,
    speed: 60,
    moves: [MOVES_DATABASE.Moonblast, MOVES_DATABASE.DazzlingGleam, MOVES_DATABASE.HyperVoice, MOVES_DATABASE.QuickAttack],
    dexNumber: 700,
    region: 'Kalos'
  },
  {
    id: 'poke_aegislash',
    name: 'Aegislash',
    type: ['Steel', 'Ghost'],
    hp: 160,
    maxHp: 160,
    attack: 110,
    defense: 140,
    spAtk: 110,
    spDef: 140,
    speed: 60,
    moves: [MOVES_DATABASE.SacredSword, MOVES_DATABASE.KingsShield, MOVES_DATABASE.ShadowBall, MOVES_DATABASE.IronTail],
    dexNumber: 681,
    region: 'Kalos'
  },
  {
    id: 'poke_talonflame',
    name: 'Talonflame',
    type: ['Fire', 'Flying'],
    hp: 178,
    maxHp: 178,
    attack: 81,
    defense: 71,
    spAtk: 74,
    spDef: 69,
    speed: 126,
    moves: [MOVES_DATABASE.Flamethrower, MOVES_DATABASE.Hurricane, MOVES_DATABASE.QuickAttack, MOVES_DATABASE.AirSlash],
    dexNumber: 663,
    region: 'Kalos'
  },
  {
    id: 'poke_goodra',
    name: 'Goodra',
    type: ['Water'],
    hp: 190,
    maxHp: 190,
    attack: 100,
    defense: 70,
    spAtk: 110,
    spDef: 150,
    speed: 80,
    moves: [MOVES_DATABASE.DracoMeteor, MOVES_DATABASE.HydroPump, MOVES_DATABASE.SludgeBomb, MOVES_DATABASE.IceBeam],
    dexNumber: 706,
    region: 'Kalos'
  },
  {
    id: 'poke_chesnaught',
    name: 'Chesnaught',
    type: ['Grass', 'Fighting'],
    hp: 188,
    maxHp: 188,
    attack: 107,
    defense: 122,
    spAtk: 74,
    spDef: 75,
    speed: 64,
    moves: [MOVES_DATABASE.LeafStorm, MOVES_DATABASE.CloseCombat, MOVES_DATABASE.GigaDrain, MOVES_DATABASE.IronTail],
    dexNumber: 652,
    region: 'Kalos'
  },
  {
    id: 'poke_delphox',
    name: 'Delphox',
    type: ['Fire', 'Psychic'],
    hp: 175,
    maxHp: 175,
    attack: 69,
    defense: 72,
    spAtk: 114,
    spDef: 100,
    speed: 104,
    moves: [MOVES_DATABASE.Flamethrower, MOVES_DATABASE.Psychic, MOVES_DATABASE.FireSpin, MOVES_DATABASE.ShadowBall],
    dexNumber: 655,
    region: 'Kalos'
  },
  {
    id: 'poke_noivern',
    name: 'Noivern',
    type: ['Dragon', 'Flying'],
    hp: 185,
    maxHp: 185,
    attack: 70,
    defense: 80,
    spAtk: 97,
    spDef: 80,
    speed: 123,
    moves: [MOVES_DATABASE.DracoMeteor, MOVES_DATABASE.Hurricane, MOVES_DATABASE.AirSlash, MOVES_DATABASE.Flamethrower],
    dexNumber: 715,
    region: 'Kalos'
  },
  {
    id: 'poke_hawlucha',
    name: 'Hawlucha',
    type: ['Fighting', 'Flying'],
    hp: 178,
    maxHp: 178,
    attack: 92,
    defense: 75,
    spAtk: 74,
    spDef: 63,
    speed: 118,
    moves: [MOVES_DATABASE.CloseCombat, MOVES_DATABASE.AirSlash, MOVES_DATABASE.Hurricane, MOVES_DATABASE.QuickAttack],
    dexNumber: 701,
    region: 'Kalos'
  },
  {
    id: 'poke_tyrantrum',
    name: 'Tyrantrum',
    type: ['Rock', 'Dragon'],
    hp: 182,
    maxHp: 182,
    attack: 121,
    defense: 119,
    spAtk: 69,
    spDef: 59,
    speed: 71,
    moves: [MOVES_DATABASE.DracoMeteor, MOVES_DATABASE.DragonClaw, MOVES_DATABASE.Outrage, MOVES_DATABASE.SkullBash],
    dexNumber: 697,
    region: 'Kalos'
  },
  {
    id: 'poke_aurorus',
    name: 'Aurorus',
    type: ['Rock', 'Ice'],
    hp: 223,
    maxHp: 223,
    attack: 77,
    defense: 72,
    spAtk: 99,
    spDef: 92,
    speed: 58,
    moves: [MOVES_DATABASE.IceBeam, MOVES_DATABASE.HydroPump, MOVES_DATABASE.Psychic, MOVES_DATABASE.Recover],
    dexNumber: 699,
    region: 'Kalos'
  },
  {
    id: 'poke_pyroar',
    name: 'Pyroar',
    type: ['Fire'],
    hp: 186,
    maxHp: 186,
    attack: 68,
    defense: 72,
    spAtk: 109,
    spDef: 66,
    speed: 106,
    moves: [MOVES_DATABASE.Flamethrower, MOVES_DATABASE.FireSpin, MOVES_DATABASE.QuickAttack, MOVES_DATABASE.DarkPulse],
    dexNumber: 668,
    region: 'Kalos'
  },
  {
    id: 'poke_clawitzer',
    name: 'Clawitzer',
    type: ['Water'],
    hp: 171,
    maxHp: 171,
    attack: 73,
    defense: 88,
    spAtk: 120,
    spDef: 89,
    speed: 59,
    moves: [MOVES_DATABASE.HydroPump, MOVES_DATABASE.AuraSphere, MOVES_DATABASE.IceBeam, MOVES_DATABASE.DarkPulse],
    dexNumber: 693,
    region: 'Kalos'
  },
  {
    id: 'poke_florges',
    name: 'Florges',
    type: ['Fairy'],
    hp: 178,
    maxHp: 178,
    attack: 65,
    defense: 68,
    spAtk: 112,
    spDef: 154,
    speed: 75,
    moves: [MOVES_DATABASE.Moonblast, MOVES_DATABASE.DazzlingGleam, MOVES_DATABASE.GigaDrain, MOVES_DATABASE.Recover],
    dexNumber: 671,
    region: 'Kalos'
  },
  {
    id: 'poke_heliolisk',
    name: 'Heliolisk',
    type: ['Electric', 'Normal'],
    hp: 162,
    maxHp: 162,
    attack: 55,
    defense: 52,
    spAtk: 109,
    spDef: 94,
    speed: 109,
    moves: [MOVES_DATABASE.Thunderbolt, MOVES_DATABASE.ElectroBall, MOVES_DATABASE.Surf, MOVES_DATABASE.QuickAttack],
    dexNumber: 695,
    region: 'Kalos'
  },

  // --- ALOLA (Gen 7) ---
  {
    id: 'poke_decidueye',
    name: 'Decidueye',
    type: ['Ghost', 'Flying'],
    hp: 178,
    maxHp: 178,
    attack: 107,
    defense: 75,
    spAtk: 100,
    spDef: 100,
    speed: 70,
    moves: [MOVES_DATABASE.LeafStorm, MOVES_DATABASE.ShadowBall, MOVES_DATABASE.Hurricane, MOVES_DATABASE.AirSlash],
    dexNumber: 724,
    region: 'Alola'
  },
  {
    id: 'poke_incineroar',
    name: 'Incineroar',
    type: ['Fire', 'Fighting'],
    hp: 195,
    maxHp: 195,
    attack: 115,
    defense: 90,
    spAtk: 80,
    spDef: 90,
    speed: 60,
    moves: [MOVES_DATABASE.Flamethrower, MOVES_DATABASE.DarkPulse, MOVES_DATABASE.CloseCombat, MOVES_DATABASE.PlayRough],
    dexNumber: 727,
    region: 'Alola'
  },
  {
    id: 'poke_primarina',
    name: 'Primarina',
    type: ['Water', 'Psychic'],
    hp: 180,
    maxHp: 180,
    attack: 74,
    defense: 74,
    spAtk: 126,
    spDef: 116,
    speed: 60,
    moves: [MOVES_DATABASE.HydroPump, MOVES_DATABASE.Moonblast, MOVES_DATABASE.Psychic, MOVES_DATABASE.ShadowBall],
    dexNumber: 730,
    region: 'Alola'
  },
  {
    id: 'poke_mimikyu',
    name: 'Mimikyu',
    type: ['Ghost', 'Psychic'],
    hp: 155,
    maxHp: 155,
    attack: 90,
    defense: 80,
    spAtk: 50,
    spDef: 105,
    speed: 96,
    moves: [MOVES_DATABASE.ShadowClaw, MOVES_DATABASE.PlayRough, MOVES_DATABASE.ShadowBall, MOVES_DATABASE.QuickAttack],
    dexNumber: 778,
    region: 'Alola'
  },
  {
    id: 'poke_lycanroc',
    name: 'Lycanroc',
    type: ['Rock'],
    hp: 175,
    maxHp: 175,
    attack: 115,
    defense: 65,
    spAtk: 55,
    spDef: 65,
    speed: 112,
    moves: [MOVES_DATABASE.SkullBash, MOVES_DATABASE.PlayRough, MOVES_DATABASE.QuickAttack, MOVES_DATABASE.IronTail],
    dexNumber: 745,
    region: 'Alola'
  },
  {
    id: 'poke_vikavolt',
    name: 'Vikavolt',
    type: ['Bug', 'Electric'],
    hp: 177,
    maxHp: 177,
    attack: 70,
    defense: 90,
    spAtk: 145,
    spDef: 75,
    speed: 43,
    moves: [MOVES_DATABASE.Thunderbolt, MOVES_DATABASE.ElectroBall, MOVES_DATABASE.AirSlash, MOVES_DATABASE.FlashCannon],
    dexNumber: 738,
    region: 'Alola'
  },
  {
    id: 'poke_toxapex',
    name: 'Toxapex',
    type: ['Poison', 'Water'],
    hp: 150,
    maxHp: 150,
    attack: 63,
    defense: 152,
    spAtk: 53,
    spDef: 142,
    speed: 35,
    moves: [MOVES_DATABASE.SludgeBomb, MOVES_DATABASE.HydroPump, MOVES_DATABASE.Surf, MOVES_DATABASE.Recover],
    dexNumber: 748,
    region: 'Alola'
  },
  {
    id: 'poke_salazzle',
    name: 'Salazzle',
    type: ['Poison', 'Fire'],
    hp: 168,
    maxHp: 168,
    attack: 64,
    defense: 60,
    spAtk: 111,
    spDef: 60,
    speed: 117,
    moves: [MOVES_DATABASE.Flamethrower, MOVES_DATABASE.SludgeBomb, MOVES_DATABASE.FireSpin, MOVES_DATABASE.DragonClaw],
    dexNumber: 758,
    region: 'Alola'
  },
  {
    id: 'poke_bewear',
    name: 'Bewear',
    type: ['Normal', 'Fighting'],
    hp: 220,
    maxHp: 220,
    attack: 125,
    defense: 80,
    spAtk: 55,
    spDef: 60,
    speed: 60,
    moves: [MOVES_DATABASE.CloseCombat, MOVES_DATABASE.PlayRough, MOVES_DATABASE.SkullBash, MOVES_DATABASE.IronTail],
    dexNumber: 760,
    region: 'Alola'
  },
  {
    id: 'poke_tsareena',
    name: 'Tsareena',
    type: ['Grass'],
    hp: 172,
    maxHp: 172,
    attack: 120,
    defense: 98,
    spAtk: 50,
    spDef: 98,
    speed: 72,
    moves: [MOVES_DATABASE.LeafStorm, MOVES_DATABASE.GigaDrain, MOVES_DATABASE.PlayRough, MOVES_DATABASE.QuickAttack],
    dexNumber: 763,
    region: 'Alola'
  },
  {
    id: 'poke_golisopod',
    name: 'Golisopod',
    type: ['Bug', 'Water'],
    hp: 175,
    maxHp: 175,
    attack: 125,
    defense: 140,
    spAtk: 60,
    spDef: 90,
    speed: 40,
    moves: [MOVES_DATABASE.HydroPump, MOVES_DATABASE.Surf, MOVES_DATABASE.IronTail, MOVES_DATABASE.SkullBash],
    dexNumber: 768,
    region: 'Alola'
  },
  {
    id: 'poke_silvally',
    name: 'Silvally',
    type: ['Normal'],
    hp: 195,
    maxHp: 195,
    attack: 95,
    defense: 95,
    spAtk: 95,
    spDef: 95,
    speed: 95,
    moves: [MOVES_DATABASE.SkullBash, MOVES_DATABASE.IronTail, MOVES_DATABASE.Flamethrower, MOVES_DATABASE.IceBeam],
    dexNumber: 773,
    region: 'Alola'
  },
  {
    id: 'poke_kommoo',
    name: 'Kommo-o',
    type: ['Dragon', 'Fighting'],
    hp: 175,
    maxHp: 175,
    attack: 110,
    defense: 125,
    spAtk: 100,
    spDef: 105,
    speed: 85,
    moves: [MOVES_DATABASE.DracoMeteor, MOVES_DATABASE.CloseCombat, MOVES_DATABASE.Outrage, MOVES_DATABASE.FlashCannon],
    dexNumber: 784,
    region: 'Alola'
  },
  {
    id: 'poke_zeraora',
    name: 'Zeraora',
    type: ['Electric'],
    hp: 188,
    maxHp: 188,
    attack: 112,
    defense: 75,
    spAtk: 102,
    spDef: 80,
    speed: 143,
    moves: [MOVES_DATABASE.Thunderbolt, MOVES_DATABASE.ElectroBall, MOVES_DATABASE.CloseCombat, MOVES_DATABASE.QuickAttack],
    dexNumber: 807,
    region: 'Alola'
  },

  // --- GALAR (Gen 8) ---
  {
    id: 'poke_cinderace',
    name: 'Cinderace',
    type: ['Fire', 'Fighting'],
    hp: 180,
    maxHp: 180,
    attack: 116,
    defense: 75,
    spAtk: 65,
    spDef: 75,
    speed: 119,
    moves: [MOVES_DATABASE.Flamethrower, MOVES_DATABASE.FireSpin, MOVES_DATABASE.CloseCombat, MOVES_DATABASE.QuickAttack],
    dexNumber: 815,
    region: 'Galar'
  },
  {
    id: 'poke_rillaboom',
    name: 'Rillaboom',
    type: ['Poison'],
    hp: 200,
    maxHp: 200,
    attack: 125,
    defense: 90,
    spAtk: 60,
    spDef: 70,
    speed: 85,
    moves: [MOVES_DATABASE.LeafStorm, MOVES_DATABASE.GigaDrain, MOVES_DATABASE.CloseCombat, MOVES_DATABASE.SkullBash],
    dexNumber: 812,
    region: 'Galar'
  },
  {
    id: 'poke_corviknight',
    name: 'Corviknight',
    type: ['Steel', 'Flying'],
    hp: 198,
    maxHp: 198,
    attack: 87,
    defense: 105,
    spAtk: 53,
    spDef: 85,
    speed: 67,
    moves: [MOVES_DATABASE.IronTail, MOVES_DATABASE.AirSlash, MOVES_DATABASE.Hurricane, MOVES_DATABASE.Recover],
    dexNumber: 823,
    region: 'Galar'
  },
  {
    id: 'poke_dragapult',
    name: 'Dragapult',
    type: ['Ghost', 'Flying'],
    hp: 188,
    maxHp: 188,
    attack: 120,
    defense: 75,
    spAtk: 100,
    spDef: 75,
    speed: 142,
    moves: [MOVES_DATABASE.DracoMeteor, MOVES_DATABASE.ShadowBall, MOVES_DATABASE.Flamethrower, MOVES_DATABASE.HydroPump],
    dexNumber: 887,
    region: 'Galar'
  },
  {
    id: 'poke_inteleon',
    name: 'Inteleon',
    type: ['Water'],
    hp: 170,
    maxHp: 170,
    attack: 85,
    defense: 65,
    spAtk: 125,
    spDef: 65,
    speed: 120,
    moves: [MOVES_DATABASE.HydroPump, MOVES_DATABASE.Surf, MOVES_DATABASE.IceBeam, MOVES_DATABASE.AirSlash],
    dexNumber: 818,
    region: 'Galar'
  },
  {
    id: 'poke_obstagoon',
    name: 'Obstagoon',
    type: ['Normal', 'Dark'],
    hp: 193,
    maxHp: 193,
    attack: 90,
    defense: 101,
    spAtk: 60,
    spDef: 81,
    speed: 95,
    moves: [MOVES_DATABASE.DarkPulse, MOVES_DATABASE.SkullBash, MOVES_DATABASE.CloseCombat, MOVES_DATABASE.IronTail],
    dexNumber: 862,
    region: 'Galar'
  },
  {
    id: 'poke_grimmsnarl',
    name: 'Grimmsnarl',
    type: ['Fairy', 'Dark'],
    hp: 195,
    maxHp: 195,
    attack: 120,
    defense: 65,
    spAtk: 95,
    spDef: 75,
    speed: 60,
    moves: [MOVES_DATABASE.PlayRough, MOVES_DATABASE.Moonblast, MOVES_DATABASE.DarkPulse, MOVES_DATABASE.Recover],
    dexNumber: 861,
    region: 'Galar'
  },
  {
    id: 'poke_toxtricity',
    name: 'Toxtricity',
    type: ['Electric', 'Poison'],
    hp: 175,
    maxHp: 175,
    attack: 98,
    defense: 70,
    spAtk: 114,
    spDef: 70,
    speed: 75,
    moves: [MOVES_DATABASE.Thunderbolt, MOVES_DATABASE.SludgeBomb, MOVES_DATABASE.ElectroBall, MOVES_DATABASE.HyperVoice],
    dexNumber: 849,
    region: 'Galar'
  },
  {
    id: 'poke_urshifu',
    name: 'Urshifu',
    type: ['Fighting', 'Dark'],
    hp: 200,
    maxHp: 200,
    attack: 130,
    defense: 100,
    spAtk: 63,
    spDef: 60,
    speed: 97,
    moves: [MOVES_DATABASE.CloseCombat, MOVES_DATABASE.DarkPulse, MOVES_DATABASE.IronTail, MOVES_DATABASE.AuraSphere],
    dexNumber: 892,
    region: 'Galar'
  },
  {
    id: 'poke_alcremie',
    name: 'Alcremie',
    type: ['Fairy'],
    hp: 165,
    maxHp: 165,
    attack: 60,
    defense: 75,
    spAtk: 110,
    spDef: 121,
    speed: 64,
    moves: [MOVES_DATABASE.Moonblast, MOVES_DATABASE.DazzlingGleam, MOVES_DATABASE.Recover, MOVES_DATABASE.Psychic],
    dexNumber: 869,
    region: 'Galar'
  },
  {
    id: 'poke_centiskorch',
    name: 'Centiskorch',
    type: ['Fire', 'Bug'],
    hp: 200,
    maxHp: 200,
    attack: 115,
    defense: 65,
    spAtk: 90,
    spDef: 90,
    speed: 65,
    moves: [MOVES_DATABASE.Flamethrower, MOVES_DATABASE.FireSpin, MOVES_DATABASE.GigaDrain, MOVES_DATABASE.Outrage],
    dexNumber: 851,
    region: 'Galar'
  },
  {
    id: 'poke_dracovish',
    name: 'Dracovish',
    type: ['Water', 'Dragon'],
    hp: 190,
    maxHp: 190,
    attack: 90,
    defense: 100,
    spAtk: 70,
    spDef: 80,
    speed: 75,
    moves: [MOVES_DATABASE.HydroPump, MOVES_DATABASE.DracoMeteor, MOVES_DATABASE.IceBeam, MOVES_DATABASE.Outrage],
    dexNumber: 882,
    region: 'Galar'
  },
  {
    id: 'poke_spectrier',
    name: 'Spectrier',
    type: ['Ghost'],
    hp: 200,
    maxHp: 200,
    attack: 65,
    defense: 60,
    spAtk: 145,
    spDef: 80,
    speed: 130,
    moves: [MOVES_DATABASE.ShadowBall, MOVES_DATABASE.DarkPulse, MOVES_DATABASE.Recover, MOVES_DATABASE.QuickAttack],
    dexNumber: 897,
    region: 'Galar'
  },
  {
    id: 'poke_glastrier',
    name: 'Glastrier',
    type: ['Ice'],
    hp: 200,
    maxHp: 200,
    attack: 145,
    defense: 130,
    spAtk: 65,
    spDef: 110,
    speed: 30,
    moves: [MOVES_DATABASE.IceBeam, MOVES_DATABASE.SkullBash, MOVES_DATABASE.IronTail, MOVES_DATABASE.CloseCombat],
    dexNumber: 896,
    region: 'Galar'
  },

  // --- PALDEA (Gen 9) ---
  {
    id: 'poke_ceruledge',
    name: 'Ceruledge',
    type: ['Fire', 'Ghost'],
    hp: 175,
    maxHp: 175,
    attack: 125,
    defense: 80,
    spAtk: 60,
    spDef: 100,
    speed: 85,
    moves: [MOVES_DATABASE.BitterBlade, MOVES_DATABASE.ShadowClaw, MOVES_DATABASE.Flamethrower, MOVES_DATABASE.DarkPulse],
    dexNumber: 937,
    region: 'Paldea'
  },
  {
    id: 'poke_meowscarada',
    name: 'Meowscarada',
    type: ['Poison', 'Ghost'],
    hp: 176,
    maxHp: 176,
    attack: 110,
    defense: 70,
    spAtk: 81,
    spDef: 70,
    speed: 123,
    moves: [MOVES_DATABASE.LeafStorm, MOVES_DATABASE.DarkPulse, MOVES_DATABASE.GigaDrain, MOVES_DATABASE.PlayRough],
    dexNumber: 908,
    region: 'Paldea'
  },
  {
    id: 'poke_skeledirge',
    name: 'Skeledirge',
    type: ['Fire', 'Ghost'],
    hp: 204,
    maxHp: 204,
    attack: 75,
    defense: 100,
    spAtk: 110,
    spDef: 75,
    speed: 66,
    moves: [MOVES_DATABASE.Flamethrower, MOVES_DATABASE.ShadowBall, MOVES_DATABASE.FireSpin, MOVES_DATABASE.Recover],
    dexNumber: 909,
    region: 'Paldea'
  },
  {
    id: 'poke_quaquaval',
    name: 'Quaquaval',
    type: ['Water', 'Fighting'],
    hp: 185,
    maxHp: 185,
    attack: 120,
    defense: 80,
    spAtk: 85,
    spDef: 75,
    speed: 85,
    moves: [MOVES_DATABASE.HydroPump, MOVES_DATABASE.CloseCombat, MOVES_DATABASE.Surf, MOVES_DATABASE.AirSlash],
    dexNumber: 912,
    region: 'Paldea'
  },
  {
    id: 'poke_tinkaton',
    name: 'Tinkaton',
    type: ['Steel', 'Psychic'],
    hp: 185,
    maxHp: 185,
    attack: 75,
    defense: 77,
    spAtk: 70,
    spDef: 105,
    speed: 94,
    moves: [MOVES_DATABASE.MeteorMash, MOVES_DATABASE.PlayRough, MOVES_DATABASE.IronTail, MOVES_DATABASE.Recover],
    dexNumber: 959,
    region: 'Paldea'
  },
  {
    id: 'poke_armarouge',
    name: 'Armarouge',
    type: ['Fire', 'Psychic'],
    hp: 185,
    maxHp: 185,
    attack: 60,
    defense: 115,
    spAtk: 125,
    spDef: 80,
    speed: 75,
    moves: [MOVES_DATABASE.Flamethrower, MOVES_DATABASE.Psychic, MOVES_DATABASE.AuraSphere, MOVES_DATABASE.FlashCannon],
    dexNumber: 936,
    region: 'Paldea'
  },
  {
    id: 'poke_koraidon',
    name: 'Koraidon',
    type: ['Fighting', 'Dragon'],
    hp: 200,
    maxHp: 200,
    attack: 135,
    defense: 115,
    spAtk: 85,
    spDef: 100,
    speed: 135,
    moves: [MOVES_DATABASE.CloseCombat, MOVES_DATABASE.Outrage, MOVES_DATABASE.DracoMeteor, MOVES_DATABASE.Flamethrower],
    dexNumber: 1007,
    region: 'Paldea'
  },
  {
    id: 'poke_miraidon',
    name: 'Miraidon',
    type: ['Electric', 'Dragon'],
    hp: 200,
    maxHp: 200,
    attack: 85,
    defense: 100,
    spAtk: 135,
    spDef: 115,
    speed: 135,
    moves: [MOVES_DATABASE.Thunderbolt, MOVES_DATABASE.DracoMeteor, MOVES_DATABASE.ElectroBall, MOVES_DATABASE.Recover],
    dexNumber: 1008,
    region: 'Paldea'
  },
  {
    id: 'poke_baxcalibur',
    name: 'Baxcalibur',
    type: ['Dragon', 'Ice'],
    hp: 215,
    maxHp: 215,
    attack: 145,
    defense: 92,
    spAtk: 75,
    spDef: 86,
    speed: 87,
    moves: [MOVES_DATABASE.DracoMeteor, MOVES_DATABASE.IceBeam, MOVES_DATABASE.Outrage, MOVES_DATABASE.IronTail],
    dexNumber: 998,
    region: 'Paldea'
  },
  {
    id: 'poke_gholdengo',
    name: 'Gholdengo',
    type: ['Steel', 'Ghost'],
    hp: 187,
    maxHp: 187,
    attack: 60,
    defense: 95,
    spAtk: 133,
    spDef: 91,
    speed: 84,
    moves: [MOVES_DATABASE.FlashCannon, MOVES_DATABASE.ShadowBall, MOVES_DATABASE.Recover, MOVES_DATABASE.DazzlingGleam],
    dexNumber: 1000,
    region: 'Paldea'
  },
  {
    id: 'poke_greattusk',
    name: 'Great Tusk',
    type: ['Ground', 'Fighting'],
    hp: 215,
    maxHp: 215,
    attack: 131,
    defense: 131,
    spAtk: 53,
    spDef: 53,
    speed: 87,
    moves: [MOVES_DATABASE.CloseCombat, MOVES_DATABASE.SkullBash, MOVES_DATABASE.IronTail, MOVES_DATABASE.PlayRough],
    dexNumber: 984,
    region: 'Paldea'
  },
  {
    id: 'poke_ironvaliant',
    name: 'Iron Valiant',
    type: ['Fairy', 'Fighting'],
    hp: 174,
    maxHp: 174,
    attack: 130,
    defense: 90,
    spAtk: 120,
    spDef: 60,
    speed: 116,
    moves: [MOVES_DATABASE.Moonblast, MOVES_DATABASE.CloseCombat, MOVES_DATABASE.DazzlingGleam, MOVES_DATABASE.ShadowClaw],
    dexNumber: 995,
    region: 'Paldea'
  },
  {
    id: 'poke_roaringmoon',
    name: 'Roaring Moon',
    type: ['Dragon', 'Dark'],
    hp: 205,
    maxHp: 205,
    attack: 139,
    defense: 71,
    spAtk: 55,
    spDef: 101,
    speed: 119,
    moves: [MOVES_DATABASE.Outrage, MOVES_DATABASE.DarkPulse, MOVES_DATABASE.Hurricane, MOVES_DATABASE.DragonClaw],
    dexNumber: 997,
    region: 'Paldea'
  },
  {
    id: 'poke_palafin',
    name: 'Palafin',
    type: ['Water'],
    hp: 200,
    maxHp: 200,
    attack: 160,
    defense: 97,
    spAtk: 106,
    spDef: 87,
    speed: 100,
    moves: [MOVES_DATABASE.HydroPump, MOVES_DATABASE.Surf, MOVES_DATABASE.IceBeam, MOVES_DATABASE.Recover],
    dexNumber: 964,
    region: 'Paldea'
  },
  {
    id: 'poke_kingambit',
    name: 'Kingambit',
    type: ['Dark', 'Steel'],
    hp: 200,
    maxHp: 200,
    attack: 135,
    defense: 120,
    spAtk: 60,
    spDef: 85,
    speed: 50,
    moves: [MOVES_DATABASE.IronTail, MOVES_DATABASE.DarkPulse, MOVES_DATABASE.ShadowClaw, MOVES_DATABASE.KingsShield],
    dexNumber: 983,
    region: 'Paldea'
  },
];

export interface NpcTrainer {
  name: string;
  role: string;
  avatar: string;
  team: string[]; // names of pokemon in team
  difficulty: 'Easy' | 'Medium' | 'Hard' | 'Champion';
  intro: string;
  outro: string;
}

export const NPC_TRAINERS: NpcTrainer[] = [
  {
    name: "Trainer 1",
    role: "UNSC Chair",
    avatar: "🤵",
    team: ["Pikachu", "Eevee", "Gengar"],
    difficulty: "Easy",
    intro: "The Security Council is now in session. Show me your debate skills on the battlefield!",
    outro: "An impressive resolution, delegate. You've won this round."
  },
  {
    name: "Trainer 2",
    role: "Director-General",
    avatar: "📋",
    team: ["Lucario", "Blastoise", "Gyarados", "Scizor"],
    difficulty: "Medium",
    intro: "As the Director-General, I ensure every committee has flawless logistics. Let's see if you can manage my perfectly coordinated team!",
    outro: "Incredible! Your battle logic is completely flawless!"
  },
  {
    name: "Trainer 3",
    role: "Model UN Veteran & Mentor",
    avatar: "🎓",
    team: ["Charizard", "Venusaur", "Gardevoir", "Sylveon", "Lugia"],
    difficulty: "Hard",
    intro: "I have won Best Delegate awards across 15 national MUNs. You're going to need a perfect strategy to defeat me.",
    outro: "Splendid! Your strategic tactical focus rivals the best diplomat I have ever mentored."
  },
  {
    name: "Trainer 4",
    role: "School Principal (The MUN Boss)",
    avatar: "👑",
    team: ["Mewtwo", "Rayquaza", "Garchomp", "Aegislash", "Kyogre", "Groudon"],
    difficulty: "Champion",
    intro: "Our Public School is built on excellence, discipline, and impact. Show me the absolute peak of your delegate strength!",
    outro: "Extraordinary! You truly embody the spirit of the School MUN 3.0!"
  },
  {
    name: "Kartik Kumar",
    role: "Head of Tech Department of whole 6v6 Pokémon, not 6v6 3v3 Pokémon",
    avatar: "⚡",
    team: ["Greninja", "Charizard", "Rayquaza", "Mewtwo", "Garchomp", "Lucario"],
    difficulty: "Champion",
    intro: "I am the Head of Tech Department of whole 6v6 Pokémon, not 6v6 3v3 Pokémon! I built this entire MUN tech system, including this simulator! Let's see if you can bypass my defenses.",
    outro: "Phenomenal! Your battle execution is unparalleled. You are the ultimate Grand Champion!"
  }
];

export const CAMPUS_STALLS = [
  { name: "Pizza Hub", item: "Cheese Burst Slice", originalPrice: 120, discountPrice: 60 },
  { name: "Chaotic Chat", item: "Gold Special Golgappa", originalPrice: 80, discountPrice: 40 },
  { name: "Waffle Wonder", item: "Nutella Bubble Waffle", originalPrice: 150, discountPrice: 75 },
  { name: "Noodle Box", item: "Veg Hakka Singapore Noodles", originalPrice: 100, discountPrice: 50 }
];
